M48
; DRILL file {KiCad 9.0.1+1} date 2025-11-23T23:33:03+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-23T23:33:03+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X106.19Y-103.203
X111.97Y-103.203
T2
X121.4Y-99.3
X123.7Y-99.3
M30
