M48
; DRILL file {KiCad 9.0.6+1} date 2025-12-13T18:46:27+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-13T18:46:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X138.29Y-73.125
X144.07Y-73.125
T2
X153.6Y-101.37
X155.9Y-101.37
T3
X131.9Y-70.1
X131.9Y-100.6
X162.4Y-70.1
X162.4Y-100.6
M30
