M48
; DRILL file {KiCad 9.0.1+1} date 2025-11-24T23:18:14+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-24T23:18:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X142.14Y-77.64
X147.92Y-77.64
T2
X153.9Y-73.75
X156.2Y-73.75
M30
